### ISSUE TITLE
Updated iTunes Connect Pricing Matrix

### ISSUE THREAD

**Issue by jstart** [affinitas/Apple-Price-Tier-Matrix-JSON#1]
For anyone who ends up here through a failed Google (like I did) there is now a private JSON API to get the pricing matrix:

https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/apps/458272450/pricing/matrix

Gist with the JSON as of today.
https://gist.github.com/jstart/822c122d12420d46703f

**Comment by Plaputta** [comment]
Thanks a lot Christopher! Very nice find!

For others stumbling upon this: The ID in the URL (4582...) must be of one of your apps and you need to be logged in to iTunesConnect.

I will no longer maintain this script, waiting for a public API and hoping that the output of the private API won't change too often...
